# Từ điển cấp độ Cụm từ (Phrase) - Tiếng Anh : Tiếng Việt
# 100 Cụm từ Tiếng Anh Quân Sự Thông Dụng Nhất

phrase_dict = {
    # Nhóm 1: Mệnh lệnh đội ngũ (Drill Commands)
    "Attention!": "Nghiêm!",
    "At ease!": "Nghỉ!",
    "Present arms!": "Chào tay!",
    "Order arms!": "Thôi chào!",
    "Fall in!": "Tập hợp!",
    "Fall out!": "Giải tán!",
    "Quick march!": "Đi đều bước!",
    "Double march!": "Chạy đều bước!",
    "Halt!": "Đứng lại!",
    "Eyes right!": "Nhìn bên phải, chào!",
    "As you were!": "Thôi (hủy bỏ mệnh lệnh)",
    "Carry on!": "Tiếp tục thực hiện nhiệm vụ!",
    "Dismissed!": "Giải tán/Cho lui!",
    "Left turn!": "Bên trái, quay!",
    "Right turn!": "Bên phải, quay!",
    "About turn!": "Đằng sau, quay!",
    
    # Nhóm 2: Chuyên ngành Công binh & Vật nổ (Sapper & EOD)
    "Detecting mines": "Đang dò mìn",
    "Clear the minefield": "Giải tỏa bãi mìn",
    "Mark the safe path": "Đánh dấu đường an toàn",
    "Disarm the bomb": "Vô hiệu hóa quả bom",
    "Set the charges": "Đặt khối bộc phá",
    "Blow the bridge": "Phá hủy cầu",
    "Construct a bunker": "Xây dựng lô cốt",
    "Breach the obstacle": "Phá vỡ vật cản",
    "Deploy the pontoon bridge": "Triển khai cầu phao",
    "Establish a perimeter": "Thiết lập vành đai bảo vệ",
    "IED spotted!": "Phát hiện thiết bị nổ tự chế!",
    "Safe distance": "Khoảng cách an toàn",
    "Controlled explosion": "Nổ có kiểm soát",
    "Dig a trench": "Đào công sự/hào",
    "Reinforce the structure": "Gia cố công trình",
    "UXO disposal": "Xử lý vật nổ chưa nổ",
    "Conduct reconnaissance": "Tiến hành trinh sát",
    "Fortify the position": "Củng cố vị trí phòng thủ",
    "Search and clear": "Tìm và quét sạch",
    
    # Nhóm 3: Tác chiến và Chiến thuật (Combat & Tactics)
    "Open fire!": "Khai hỏa!",
    "Cease fire!": "Ngừng bắn!",
    "Hold fire!": "Tạm dừng bắn!",
    "Cover me!": "Yểm trợ cho tôi!",
    "Move out!": "Xuất phát/Tiến ra!",
    "Take cover!": "Tìm chỗ ẩn nấp!",
    "Enemy spotted!": "Phát hiện quân địch!",
    "Target neutralized!": "Đã tiêu diệt mục tiêu!",
    "Incoming fire!": "Địch đang bắn tới!",
    "Return fire!": "Bắn trả!",
    "Flank the enemy": "Đánh vào sườn địch",
    "Full retreat": "Rút lui toàn bộ",
    "Advance to contact": "Tiến quân để tiếp xúc địch",
    "Suppressive fire": "Bắn áp chế",
    "Engagement area": "Khu vực giao tranh",
    "On the double": "Nhanh chóng",
    "Watch your six": "Cẩn thận phía sau lưng",
    "Maintain radio silence": "Giữ yên lặng vô tuyến",
    "Medical assistance needed": "Cần hỗ trợ y tế",
    
    # Nhóm 4: Thông tin vô tuyến (Radio Procedures)
    "Roger that": "Rõ, nghe rõ",
    "Copy that": "Đã nhận thông tin",
    "Over and out": "Hết và ngắt liên lạc",
    "Do you read me?": "Nghe tôi rõ không?",
    "Loud and clear": "Nghe rất rõ",
    "Say again": "Nhắc lại nội dung",
    "Negative": "Không/Không đồng ý",
    "Affirmative": "Đúng/Đồng ý",
    "Wilco": "Sẽ thực hiện mệnh lệnh",
    "Radio check": "Kiểm tra tín hiệu vô tuyến",
    "Stand by": "Đợi lệnh/Chờ máy",
    "Go ahead": "Mời nói/Tiếp tục đi",
    
    # Nhóm 5: Báo cáo và Trạng thái (Reporting & Status)
    "Mission accomplished": "Nhiệm vụ hoàn thành",
    "Mission aborted": "Hủy bỏ nhiệm vụ",
    "Casualty evacuation": "Di tản thương vong",
    "Situation Report": "Báo cáo tình hình",
    "Under fire": "Đang bị tấn công",
    "Low on ammo": "Sắp hết đạn",
    "Area secure": "Khu vực đã an toàn",
    "Visual contact": "Liên lạc bằng mắt thường",
    "Identify yourself": "Xác nhận danh tính",
    "Rules of engagement": "Quy tắc giao chiến",
    "Chain of command": "Chuỗi mệnh lệnh/Cấp bậc chỉ huy",
    "Standard Operating Procedure": "Quy trình tác chiến tiêu chuẩn",
    
    # Nhóm 6: Cụm từ thông dụng khác (General Phrases)
    "Drop your weapon!": "Bỏ vũ khí xuống!",
    "Put your hands up!": "Giơ tay lên!",
    "Don't move!": "Đứng im!",
    "Friend or foe?": "Bạn hay thù?",
    "Password please": "Cho biết mật khẩu",
    "Secure the perimeter": "Đảm bảo an toàn vành đai",
    "Check your gear": "Kiểm tra trang thiết bị",
    "Zero hour": "Giờ G",
    "In the line of duty": "Trong khi làm nhiệm vụ",
    "Collateral damage": "Thiệt hại ngoài dự kiến",
    "Friendly fire": "Bắn nhầm đồng đội",
    "Search and rescue": "Tìm kiếm và cứu nạn",
    "Combat readiness": "Sẵn sàng chiến đấu",
    "Deployment orders": "Lệnh triển khai quân",
    "Awaiting orders": "Đang chờ mệnh lệnh",
    "By the book": "Làm đúng quy định",
    "Code red": "Cảnh báo mức độ đỏ",
    "Infiltration": "Sự thâm nhập",
    "Point of entry": "Điểm xâm nhập",
    "Extraction point": "Điểm rút quân",
    "All clear": "Tất cả đã an toàn",
    "Lock and load": "Nạp đạn và sẵn sàng bắn",
}

# Phiên âm quốc tế (IPA) cho 100 cụm từ quân sự
phrase_ipa_dict = {
    # Nhóm 1: Mệnh lệnh đội ngũ
    "Attention!": "əˈtɛnʃən",
    "At ease!": "æt iːz",
    "Present arms!": "ˈprɛzənt ɑːrmz",
    "Order arms!": "ˈɔːrdər ɑːrmz",
    "Fall in!": "fɔːl ɪn",
    "Fall out!": "fɔːl aʊt",
    "Quick march!": "kwɪk mɑːrtʃ",
    "Double march!": "ˈdʌbəl mɑːrtʃ",
    "Halt!": "hɔːlt",
    "Eyes right!": "aɪz raɪt",
    "As you were!": "əz juː wɜːr",
    "Carry on!": "ˈkæri ɑːn",
    "Dismissed!": "dɪsˈmɪst",
    "Left turn!": "lɛft tɜːrn",
    "Right turn!": "raɪt tɜːrn",
    "About turn!": "əˈbaʊt tɜːrn",
    
    # Nhóm 2: Chuyên ngành Công binh
    "Detecting mines": "dɪˈtɛktɪŋ maɪnz",
    "Clear the minefield": "klɪr ðə ˈmaɪnˌfild",
    "Mark the safe path": "mɑːrk ðə seɪf pæθ",
    "Disarm the bomb": "dɪsˈɑːrm ðə bɑːm",
    "Set the charges": "sɛt ðə ˈtʃɑːrdʒɪz",
    "Blow the bridge": "bloʊ ðə brɪdʒ",
    "Construct a bunker": "kənˈstrʌkt ə ˈbʌŋkər",
    "Breach the obstacle": "briːtʃ ðə ˈɑːbstækəl",
    "Deploy the pontoon bridge": "dɪˈplɔɪ ðə pɑːnˈtuːn brɪdʒ",
    "Establish a perimeter": "ɪsˈtæblɪʃ ə pəˈrɪmɪtər",
    "IED spotted!": "ˌaɪiːˈɛd ˈspɑːtɪd",
    "Safe distance": "seɪf ˈdɪstəns",
    "Controlled explosion": "kənˈtroʊld ɪkˈsploʊʒən",
    "Dig a trench": "dɪɡ ə trɛntʃ",
    "Reinforce the structure": "ˌriːɪnˈfɔːrs ðə ˈstrʌktʃər",
    "UXO disposal": "ˌjuːɛksˈoʊ dɪsˈpoʊzəl",
    "Conduct reconnaissance": "ˈkɑːndʌkt ˌrɛknəˈsæns",
    "Fortify the position": "ˈfɔːrtɪˌfaɪ ðə pəˈzɪʃən",
    "Search and clear": "sɜːrtʃ ənd klɪr",
    
    # Nhóm 3: Tác chiến
    "Open fire!": "ˈoʊpən ˈfaɪər",
    "Cease fire!": "siːs ˈfaɪər",
    "Hold fire!": "hoʊld ˈfaɪər",
    "Cover me!": "ˈkʌvər mi",
    "Move out!": "muːv aʊt",
    "Take cover!": "teɪk ˈkʌvər",
    "Enemy spotted!": "ˈɛnəmi ˈspɑːtɪd",
    "Target neutralized!": "ˈtɑːrɡɪt ˈnuːtrəˌlaɪzd",
    "Incoming fire!": "ˈɪnˌkʌmɪŋ ˈfaɪər",
    "Return fire!": "rɪˈtɜːrn ˈfaɪər",
    "Flank the enemy": "flæŋk ðə ˈɛnəmi",
    "Full retreat": "fʊl rɪˈtriːt",
    "Advance to contact": "ədˈvæns tuː ˈkɑːntækt",
    "Suppressive fire": "səˈprɛsɪv ˈfaɪər",
    "Engagement area": "ɪnˈɡeɪdʒmənt ˈɛriə",
    "On the double": "ɑːn ðə ˈdʌbəl",
    "Watch your six": "wɑːtʃ jər sɪks",
    "Maintain radio silence": "ˈmeɪnˌteɪn ˈreɪdioʊ ˈsaɪləns",
    "Medical assistance needed": "ˈmɛdɪkəl əˈsɪstəns ˈnidɪd",
    
    # Nhóm 4: Thông tin vô tuyến
    "Roger that": "ˈrɑːdʒər ðæt",
    "Copy that": "ˈkɑːpi ðæt",
    "Over and out": "ˈoʊvər ənd aʊt",
    "Do you read me?": "duː juː rid mi",
    "Loud and clear": "laʊd ənd klɪr",
    "Say again": "seɪ əˈɡɛn",
    "Negative": "ˈnɛɡətɪv",
    "Affirmative": "əˈfɜːrmətɪv",
    "Wilco": "ˈwɪlˌkoʊ",
    "Radio check": "ˈreɪdioʊ tʃɛk",
    "Stand by": "stænd baɪ",
    "Go ahead": "ɡoʊ əˈhɛd",
    
    # Nhóm 5: Báo cáo
    "Mission accomplished": "ˈmɪʃən ˈækkɑːmplɪʃt",
    "Mission aborted": "ˈmɪʃən əˈbɔːrtɪd",
    "Casualty evacuation": "ˈkæʒuəlti ɛvækjuˈeɪʃən",
    "Situation Report": "ˌsɪtʃuˈeɪʃən rɪˈpɔːrt",
    "Under fire": "ˈʌndər ˈfaɪər",
    "Low on ammo": "loʊ ɑːn ˈæmoʊ",
    "Area secure": "ˈɛriə sɪˈkjʊr",
    "Visual contact": "ˈvɪʒuəl ˈkɑːntækt",
    "Identify yourself": "aɪˈdɛntɪˌfaɪ jɔːrˈsɛlf",
    "Rules of engagement": "ˈrulz əv ɪnˈɡeɪdʒmənt",
    "Chain of command": "tʃeɪn əv kəˈmænd",
    "Standard Operating Procedure": "ˈstændərd ˌɑːpəˈreɪtɪŋ ˈproʊsiːdʒər",
    
    # Nhóm 6: Cụm từ chung
    "Drop your weapon!": "drɑːp jər ˈwɛpən",
    "Put your hands up!": "pʊt jər hændz ʌp",
    "Don't move!": "doʊnt muːv",
    "Friend or foe?": "frɛnd ɔːr foʊ",
    "Password please": "ˈpæswɜːrd pliːz",
    "Secure the perimeter": "sɪˈkjʊr ðə pəˈrɪmɪtər",
    "Check your gear": "tʃɛk jər ɡɪr",
    "Zero hour": "ˈziroʊ aʊər",
    "In the line of duty": "ɪn ðə laɪn əv ˈduːti",
    "Collateral damage": "kəˈlætərəl ˈdæmɪdʒ",
    "Friendly fire": "ˈfrɛndli ˈfaɪər",
    "Search and rescue": "sɜːrtʃ ənd ˈrɛskjuː",
    "Combat readiness": "ˈkɑːmbæt ˈrɛdɪnəs",
    "Deployment orders": "dɪˈplɔɪmənt ˈɔːrdərz",
    "Awaiting orders": "əˈweɪtɪŋ ˈɔːrdərz",
    "By the book": "baɪ ðə bʊk",
    "Code red": "koʊd rɛd",
    "Infiltration": "ˌɪnfɪlˈtreɪʃən",
    "Point of entry": "pɔɪnt əv ˈɛntri",
    "Extraction point": "ɪkˈstrækʃən pɔɪnt",
    "All clear": "ɔːl klɪr",
    "Lock and load": "lɑːk ənd loʊd",
}