# Từ điển cấp độ Câu (Sentence) - Tiếng Anh : Tiếng Việt
# 100 Câu Tiếng Anh Quân Sự Hoàn Chỉnh

sentence_dict = {
    # Nhóm 1: Chuyên ngành Công binh & Rà phá bom mìn (30 câu)
    "The combat engineers are clearing the main supply route.": "Các kỹ sư công binh đang dọn sạch đường cấp liệu chính.",
    "We have detected a suspicious object near the bridge.": "Chúng tôi đã phát hiện một vật thể đáng ngờ gần cầu.",
    "Use the metal detector to sweep the area for landmines.": "Sử dụng máy dò kim loại để quét khu vực tìm mìn bộ binh.",
    "Mark the safe lane with white tape for the infantry.": "Đánh dấu làn đường an toàn bằng băng trắng cho bộ binh.",
    "This unexploded ordnance is extremely unstable.": "Vật nổ chưa nổ này cực kỳ bất ổn.",
    "We need to set the charges to destroy the enemy fortification.": "Chúng tôi cần đặt khối bộc phá để phá hủy công sự của địch.",
    "The bridge was severely damaged by an improvised explosive device.": "Cây cầu bị hư hại nặng do một thiết bị nổ tự chế.",
    "How many anti-tank mines were found in this sector?": "Có bao nhiêu mìn chống xe tăng được tìm thấy trong khu vực này?",
    "The sapper unit is preparing to breach the wire obstacle.": "Đơn vị công binh đang chuẩn bị vô hiệu hóa vật cản dây thép.",
    "Dig a trench at least one meter deep for protection.": "Đào hào sâu ít nhất một mét để bảo vệ.",
    "We must deploy the pontoon bridge before the sun rises.": "Chúng tôi phải triển khai cầu phao trước khi mặt trời mọc.",
    "The soil condition is not suitable for heavy vehicle movement.": "Điều kiện đất không phù hợp cho chuyển động phương tiện nặng.",
    "Requesting immediate disposal of a discovered sea mine.": "Yêu cầu xử lý ngay một thủy lôi đã khám phá.",
    "Ensure the detonator is disconnected before transport.": "Đảm bảo ngòi nổ được ngắt trước khi vận chuyển.",
    "This bunker is built with reinforced concrete.": "Lô cốt này được xây bằng bê tông cốt thép.",
    "The minefield extends five hundred meters to the east.": "Bãi mìn kéo dài năm trăm mét về phía đông.",
    "We use remote-controlled robots to defuse the bomb.": "Chúng tôi sử dụng robot điều khiển từ xa để tháo bom.",
    "Clear all obstacles to allow the tanks to pass through.": "Dọn sạch tất cả vật cản để cho phép xe tăng đi qua.",
    "The explosion created a crater three meters wide.": "Vụ nổ tạo ra một hố sâu ba mét.",
    "Check the structural integrity of the bridge before crossing.": "Kiểm tra toàn vẹn kết cấu của cầu trước khi vượt.",
    "Combat engineers are responsible for road construction and repair.": "Các kỹ sư công binh chịu trách nhiệm xây dựng và sửa chữa đường.",
    "We are setting up a water purification point for the battalion.": "Chúng tôi đang thiết lập một điểm thanh lọc nước cho tiểu đoàn.",
    "The enemy has placed booby traps inside the building.": "Địch đã đặt bẫy độc trong tòa nhà.",
    "Please provide the coordinates of the minefield.": "Vui lòng cung cấp tọa độ của bãi mìn.",
    "The blast radius of this explosive is fifty meters.": "Bán kính nổ của chất nổ này là năm mươi mét.",
    "We need to camouflage the command post immediately.": "Chúng tôi cần che giấu bộ chỉ huy ngay lập tức.",
    "The demining operation will take at least three days.": "Hoạt động rà phá mìn sẽ mất ít nhất ba ngày.",
    "Wear your protective suit before entering the contaminated area.": "Mặc trang phục bảo vệ trước khi vào khu vực bị ô nhiễm.",
    "Secure the perimeter while the sappers work on the IED.": "Đảm bảo an toàn vành đai trong khi công binh làm việc với IED.",
    "All personnel must stay at a safe distance during the blast.": "Tất cả nhân viên phải ở một khoảng cách an toàn trong khi nổ.",
    
    # Nhóm 2: Mệnh lệnh & Tác chiến (25 câu)
    "Fall in and prepare for the morning briefing.": "Tập hợp và chuẩn bị cho buổi họp báo cáo buổi sáng.",
    "Move out to the extraction point immediately.": "Xuất phát đến điểm rút quân ngay lập tức.",
    "Maintain radio silence until you reach the target.": "Giữ im lặng vô tuyến cho đến khi bạn đến mục tiêu.",
    "The enemy is retreating towards the northern forest.": "Địch đang rút lui về phía rừng phía bắc.",
    "Open fire only when I give the command.": "Khai hỏa chỉ khi tôi phát lệnh.",
    "We are taking heavy fire from the high ground.": "Chúng tôi đang bị bắn nặng từ vị trí cao.",
    "Requesting air support at coordinates Alpha-Niner.": "Yêu cầu hỗ trợ không quân ở tọa độ Alpha-Niner.",
    "Establish a defensive perimeter around the base.": "Thiết lập vành đai phòng thủ xung quanh căn cứ.",
    "The scouts are conducting reconnaissance in the valley.": "Các trinh sát đang tiến hành trinh sát ở thung lũng.",
    "We need to reinforce our left flank before the attack.": "Chúng tôi cần gia cố sườn trái trước cuộc tấn công.",
    "Do not engage the enemy without further orders.": "Không giao tranh với địch mà không có lệnh thêm.",
    "Cover the infantry while they cross the open field.": "Yểm trợ bộ binh trong khi họ vượt qua cánh đồng mở.",
    "How many casualties did the unit sustain?": "Đơn vị chịu bao nhiêu thương vong?",
    "The mission has been compromised, return to base.": "Nhiệm vụ đã bị lộ, quay trở về căn cứ.",
    "Search the prisoners for any hidden weapons or maps.": "Khám xét tù nhân để tìm vũ khí hoặc bản đồ ẩn giấu.",
    "We have visual contact with the enemy patrol.": "Chúng tôi có liên lạc bằng mắt thường với tuần tra địch.",
    "Suppress the enemy fire so we can move forward.": "Áp chế bắn của địch để chúng tôi có thể tiến lên.",
    "Keep your head down and stay in the trench.": "Cúi đầu xuống và ở trong hào.",
    "The assault will begin at zero-six-hundred hours.": "Cuộc tấn công sẽ bắt đầu lúc 06:00.",
    "Target neutralized, proceed to the next objective.": "Mục tiêu đã bị vô hiệu hóa, tiến tới mục tiêu tiếp theo.",
    "We are running low on ammunition and medical supplies.": "Chúng tôi sắp hết đạn dược và vật tư y tế.",
    "Secure the landing zone for the transport helicopters.": "Đảm bảo an toàn khu hạ cánh cho trực thăng vận chuyển.",
    "Watch out for enemy snipers in the urban area.": "Cẩn thận các xạ thủ tỉa của địch trong khu vực thành phố.",
    "The battalion is moving in a staggered column formation.": "Tiểu đoàn đang di chuyển theo đội hình cột cách quãng.",
    "Hold your position until the reinforcements arrive.": "Giữ vị trí của bạn cho đến khi viện binh đến.",
    
    # Nhóm 3: Thông tin vô tuyến & Báo cáo (20 câu)
    "This is Eagle One, do you copy? Over.": "Đây là Eagle One, bạn có nghe rõ không? Over.",
    "I read you loud and clear, proceed with your report.": "Tôi nghe bạn rất rõ, tiếp tục báo cáo của bạn.",
    "Say again your last transmission, signal is weak.": "Nhắc lại truyền tải cuối cùng của bạn, tín hiệu yếu.",
    "We have reached the objective, mission accomplished.": "Chúng tôi đã đạt được mục tiêu, nhiệm vụ hoàn thành.",
    "Requesting a Situation Report from all units.": "Yêu cầu báo cáo tình hình từ tất cả các đơn vị.",
    "The convoy is under attack, requesting immediate backup.": "Đoàn xe đang bị tấn công, yêu cầu tiếp viện ngay lập tức.",
    "Identify yourself before approaching the checkpoint.": "Xác nhận danh tính của bạn trước khi tiếp cận trạm kiểm soát.",
    "Roger that, we will stand by for further instructions.": "Rõ, chúng tôi sẽ chờ hướng dẫn thêm.",
    "All units, be advised of enemy movement in sector four.": "Tất cả các đơn vị, chú ý đến chuyển động của địch ở khu vực bốn.",
    "What is your current status and location?": "Tình trạng và vị trí hiện tại của bạn là gì?",
    "We have one priority casualty requiring evacuation.": "Chúng tôi có một thương vong ưu tiên cần sơ tán.",
    "The radio frequency has been jammed by the enemy.": "Tần số vô tuyến đã bị địch cản nhiễu.",
    "Confirm receipt of the new rules of engagement.": "Xác nhận nhận được quy tắc giao chiến mới.",
    "Use the phonetic alphabet to spell the location.": "Sử dụng bảng chữ cái phiên âm để đánh vần vị trí.",
    "Our GPS signal is lost, switching to map and compass.": "Tín hiệu GPS của chúng tôi bị mất, chuyển sang bản đồ và la bàn.",
    "Report any suspicious activity to the headquarters.": "Báo cáo bất kỳ hoạt động đáng ngờ nào cho bộ chỉ huy.",
    "Maintain contact with the friendly forces on your right.": "Duy trì liên lạc với lực lượng thân thiện ở bên phải bạn.",
    "All clear, the area has been secured.": "Tất cả đều an toàn, khu vực đã được đảm bảo an toàn.",
    "Affirmative, the supplies will arrive in ten minutes.": "Đúng, vật tư sẽ đến trong mười phút.",
    "Out. (Kết thúc liên lạc hoàn toàn).": "Out.",
    
    # Nhóm 4: Huấn luyện & Kỷ luật (25 câu)
    "Discipline is the backbone of a strong army.": "Kỷ luật là xương sống của một quân đội mạnh.",
    "You must follow the standard operating procedures at all times.": "Bạn phải tuân theo quy trình tác chiến tiêu chuẩn mọi lúc.",
    "All soldiers must keep their weapons clean and ready.": "Tất cả binh lính phải giữ vũ khí của họ sạch sẽ và sẵn sàng.",
    "This exercise simulates a real combat environment.": "Bài tập này mô phỏng một môi trường chiến đấu thực tế.",
    "Pay attention to the safety regulations during live-fire drills.": "Chú ý đến các quy định an toàn trong diễn tập bắn thực.",
    "Every soldier is responsible for their own gear.": "Mỗi binh lính chịu trách nhiệm về thiết bị của họ.",
    "Practice makes perfect in mine clearance operations.": "Luyện tập làm cho hành động hoàn hảo trong hoạt động rà phá mìn.",
    "You need to improve your reaction time in the field.": "Bạn cần cải thiện thời gian phản ứng của mình trong thực địa.",
    "Physical fitness is essential for every combat engineer.": "Sức khỏe thể chất là cần thiết cho mỗi kỹ sư công binh.",
    "The commander will inspect the barracks this afternoon.": "Chỉ huy sẽ kiểm tra doanh trại chiều nay.",
    "Learn how to read military maps and grid coordinates.": "Học cách đọc bản đồ quân sự và tọa độ lưới.",
    "First aid training is mandatory for all personnel.": "Đào tạo sơ cứu là bắt buộc cho tất cả nhân viên.",
    "Do not leave your post without being properly relieved.": "Không rời khỏi vị trí của bạn mà không được thay thế đúng cách.",
    "Loyalty and courage are the values of our unit.": "Lòng trung thành và can đảm là giá trị của đơn vị chúng tôi.",
    "The trainees are learning how to use the new detectors.": "Các học viên đang học cách sử dụng các máy dò mới.",
    "Check your gas mask for any leaks before the drill.": "Kiểm tra mặt nạ phòng độc của bạn có rò rỉ nào trước diễn tập.",
    "We are conducting a joint exercise with the air force.": "Chúng tôi đang tiến hành một bài tập chung với không quân.",
    "Follow the chain of command for all formal requests.": "Tuân theo chuỗi mệnh lệnh cho tất cả các yêu cầu chính thức.",
    "You must pass the obstacle course within five minutes.": "Bạn phải vượt qua khóa học chướng ngại vật trong vòng năm phút.",
    "Survival skills are crucial in a long-term operation.": "Kỹ năng sinh tồn rất quan trọng trong một hoạt động dài hạn.",
    "The debriefing will start immediately after the mission.": "Cuộc họp làm việc sẽ bắt đầu ngay sau nhiệm vụ.",
    "Always wear your helmet and bulletproof vest in the field.": "Luôn mặc mũ cối và áo chống đạn khi ở thực địa.",
    "Knowledge of foreign languages is an advantage in peacekeeping.": "Kiến thức ngoại ngữ là một lợi thế trong gìn giữ hòa bình.",
    "Stay alert and never underestimate the enemy.": "Hãy cảnh giác và không bao giờ đánh giá thấp địch.",
    "Professionalism is expected from every member of this team.": "Sự chuyên nghiệp được mong đợi từ mỗi thành viên của đội này.",
}

# Phiên âm quốc tế (IPA) cho 100 câu quân sự
sentence_ipa_dict = {
    # Nhóm 1: Công binh
    "The combat engineers are clearing the main supply route.": "ðə ˈkɑːmbæt ɛndʒɪˈnɪrz ɑːr ˈklɪrɪŋ ðə meɪn səˈplaɪ ruːt",
    "We have detected a suspicious object near the bridge.": "wi hæv dɪˈtɛktɪd ə səˈspɪʃəs ˈɑːbdʒɛkt nɪr ðə brɪdʒ",
    "Use the metal detector to sweep the area for landmines.": "juːz ðə ˈmɛtəl dɪˈtɛktər tuː swip ðə ˈɛriə fɔːr ˈlændˌmaɪnz",
    "Mark the safe lane with white tape for the infantry.": "mɑːrk ðə seɪf leɪn wɪð waɪt teɪp fɔːr ðə ˈɪnfəntri",
    "This unexploded ordnance is extremely unstable.": "ðɪs ʌnɪkˈsploʊdɪd ˈɔːrdnəns ɪz ɪkˈstriːmli ʌnˈsteɪbəl",
    "We need to set the charges to destroy the enemy fortification.": "wi niːd tuː sɛt ðə ˈtʃɑːrdʒɪz tuː dɪˈstrɔɪ ðə ˈɛnəmi ˌfɔːrtɪfɪˈkeɪʃən",
    "The bridge was severely damaged by an improvised explosive device.": "ðə brɪdʒ wəz sɪˈvɪrli ˈdæmɪdʒd baɪ əˌn ɪmˈprɑːvaɪzd ɪkˈsploʊsɪv dɪˈvaɪs",
    "How many anti-tank mines were found in this sector?": "haʊ ˈmɛni ˈæntiˌtæŋk maɪnz wɜːr faʊnd ɪn ðɪs ˈsɛktər",
    "The sapper unit is preparing to breach the wire obstacle.": "ðə ˈsæpər ˈjuːnɪt ɪz prɪˈpɛrɪŋ tuː briːtʃ ðə ˈwaɪər ˈɑːbstækəl",
    "Dig a trench at least one meter deep for protection.": "dɪɡ ə trɛntʃ æt liːst wʌn ˈmitər dip fɔːr prəˈtɛkʃən",
    "We must deploy the pontoon bridge before the sun rises.": "wi məst dɪˈplɔɪ ðə pɑːnˈtuːn brɪdʒ bɪˈfɔːr ðə sʌn ˈraɪzɪz",
    "The soil condition is not suitable for heavy vehicle movement.": "ðə sɔɪl kənˈdɪʃən ɪz nɑːt ˈsuːtəbəl fɔːr ˈhɛvi ˈviːɪkəl ˈmuːvmənt",
    "Requesting immediate disposal of a discovered sea mine.": "rɪˈkwɛstɪŋ ɪˈmiːdiət dɪsˈpoʊzəl əv ə dɪsˈkʌvərd siː maɪn",
    "Ensure the detonator is disconnected before transport.": "ɛnˈʃʊr ðə ˈdɛtəˌneɪtər ɪz ˌdɪskəˈnɛktɪd bɪˈfɔːr ˈtrænspɔːrt",
    "This bunker is built with reinforced concrete.": "ðɪs ˈbʌŋkər ɪz bɪlt wɪð ˌriːɪnˈfɔːrst ˈkɑːnˌkriːt",
    "The minefield extends five hundred meters to the east.": "ðə ˈmaɪnˌfild ɪkˈstɛndz faɪv ˈhʌndrəd ˈmitərz tuː ðə iːst",
    "We use remote-controlled robots to defuse the bomb.": "wi juːz rɪˈmoʊt kənˈtroʊld ˈroʊˌbɑːts tuː dɪˈfjuːz ðə bɑːm",
    "Clear all obstacles to allow the tanks to pass through.": "klɪr ɔːl ˈɑːbstækəlz tuː əˈlaʊ ðə tæŋks tuː pæs θruː",
    "The explosion created a crater three meters wide.": "ðə ɪkˈsploʊʒən kriˈeɪtɪd ə ˈkreɪtər θriː ˈmitərz waɪd",
    "Check the structural integrity of the bridge before crossing.": "tʃɛk ðə ˈstrʌktʃərəl ɪnˈtɛɡrəti əv ðə brɪdʒ bɪˈfɔːr ˈkrɔːsɪŋ",
    "Combat engineers are responsible for road construction and repair.": "ˈkɑːmbæt ɛndʒɪˈnɪrz ɑːr rɪˈspɑːnsɪbəl fɔːr roʊd kənˈstrʌkʃən ənd rɪˈpɛr",
    "We are setting up a water purification point for the battalion.": "wi ɑːr ˈsɛtɪŋ ʌp ə ˈwɔːtər ˌpjʊrɪfɪˈkeɪʃən pɔɪnt fɔːr ðə bəˈtæliən",
    "The enemy has placed booby traps inside the building.": "ðə ˈɛnəmi həz pleɪst ˈbuːbi træps ɪnˈsaɪd ðə ˈbɪldɪŋ",
    "Please provide the coordinates of the minefield.": "pliːz prəˈvaɪd ðə koʊˈɔːrdənɪts əv ðə ˈmaɪnˌfild",
    "The blast radius of this explosive is fifty meters.": "ðə blæst ˈreɪdiəs əv ðɪs ɪkˈsploʊsɪv ɪz ˈfɪfti ˈmitərz",
    "We need to camouflage the command post immediately.": "wi niːd tuː ˈkæməflɑːʒ ðə kəˈmænd poʊst ɪˈmiːdiətli",
    "The demining operation will take at least three days.": "ðə dɪˈmaɪnɪŋ ˌɑːpəˈreɪʃən wɪl teɪk æt liːst θriː deɪz",
    "Wear your protective suit before entering the contaminated area.": "wɛr jər prəˈtɛktɪv suːt bɪˈfɔːr ˈɛntərɪŋ ðə kənˈtæmɪˌneɪtɪd ˈɛriə",
    "Secure the perimeter while the sappers work on the IED.": "sɪˈkjʊr ðə pəˈrɪmɪtər waɪl ðə ˈsæpərz wɜːrk ɑːn ðə ˌaɪiːˈɛd",
    "All personnel must stay at a safe distance during the blast.": "ɔːl ˈpɜːrsəˌnɛl məst steɪ æt ə seɪf ˈdɪstəns ˈdʊrɪŋ ðə blæst",
    
    # Nhóm 2: Mệnh lệnh & Tác chiến
    "Fall in and prepare for the morning briefing.": "fɔːl ɪn ənd prɪˈpɛr fɔːr ðə ˈmɔːrnɪŋ ˈbriːfɪŋ",
    "Move out to the extraction point immediately.": "muːv aʊt tuː ðə ɪkˈstrækʃən pɔɪnt ɪˈmiːdiətli",
    "Maintain radio silence until you reach the target.": "ˈmeɪnˌteɪn ˈreɪdioʊ ˈsaɪləns ənˈtɪl juː ritʃ ðə ˈtɑːrɡɪt",
    "The enemy is retreating towards the northern forest.": "ðə ˈɛnəmi ɪz rɪˈtriːtɪŋ ˈtɔːrdz ðə ˈnɔːrðərn ˈfɔːrɪst",
    "Open fire only when I give the command.": "ˈoʊpən ˈfaɪər ˈoʊnli wɛn aɪ ɡɪv ðə kəˈmænd",
    "We are taking heavy fire from the high ground.": "wi ɑːr ˈteɪkɪŋ ˈhɛvi ˈfaɪər frəm ðə haɪ ɡraʊnd",
    "Requesting air support at coordinates Alpha-Niner.": "rɪˈkwɛstɪŋ ɛr səˈpɔːrt æt koʊˈɔːrdənɪts ˈælfə ˈnaɪnər",
    "Establish a defensive perimeter around the base.": "ɪsˈtæblɪʃ ə dɪˈfɛnsɪv pəˈrɪmɪtər əˈraʊnd ðə beɪs",
    "The scouts are conducting reconnaissance in the valley.": "ðə skaʊts ɑːr kənˈdʌktɪŋ ˌrɛknəˈsæns ɪn ðə ˈvæli",
    "We need to reinforce our left flank before the attack.": "wi niːd tuː ˌriːɪnˈfɔːrs aʊr lɛft flæŋk bɪˈfɔːr ðə əˈtæk",
    "Do not engage the enemy without further orders.": "duː nɑːt ɪnˈɡeɪdʒ ðə ˈɛnəmi wɪðˈaʊt ˈfɜːðər ˈɔːrdərz",
    "Cover the infantry while they cross the open field.": "ˈkʌvər ðə ˈɪnfəntri waɪl ðeɪ krɔːs ðə ˈoʊpən fild",
    "How many casualties did the unit sustain?": "haʊ ˈmɛni ˈkæʒuəltiz dɪd ðə ˈjuːnɪt səsˈteɪn",
    "The mission has been compromised, return to base.": "ðə ˈmɪʃən həz bɪn ˈkɑːmprəˌmaɪzd rɪˈtɜːrn tuː beɪs",
    "Search the prisoners for any hidden weapons or maps.": "sɜːrtʃ ðə ˈprɪzənərz fɔːr ˈɛni ˈhɪdən ˈwɛpənz ɔːr mæps",
    "We have visual contact with the enemy patrol.": "wi hæv ˈvɪʒuəl ˈkɑːntækt wɪð ðə ˈɛnəmi pəˈtroʊl",
    "Suppress the enemy fire so we can move forward.": "səˈprɛs ðə ˈɛnəmi ˈfaɪər soʊ wi kæn muːv ˈfɔːrwərd",
    "Keep your head down and stay in the trench.": "kip jər hɛd daʊn ənd steɪ ɪn ðə trɛntʃ",
    "The assault will begin at zero-six-hundred hours.": "ðə əˈsɔːlt wɪl bɪˈɡɪn æt ˈziroʊ sɪks ˈhʌndrəd ˈaʊərz",
    "Target neutralized, proceed to the next objective.": "ˈtɑːrɡɪt ˈnuːtrəˌlaɪzd proʊˈsid tuː ðə nɛkst əbˈdʒɛktɪv",
    "We are running low on ammunition and medical supplies.": "wi ɑːr ˈrʌnɪŋ loʊ ɑːn əˌmjuˈnɪʃən ənd ˈmɛdɪkəl səˈplaɪz",
    "Secure the landing zone for the transport helicopters.": "sɪˈkjʊr ðə ˈlændɪŋ zoʊn fɔːr ðə ˈtrænspɔːrt ˈhɛlɪkɑːptərz",
    "Watch out for enemy snipers in the urban area.": "wɑːtʃ aʊt fɔːr ˈɛnəmi ˈsnaɪpərz ɪn ðə ˈɜːrbən ˈɛriə",
    "The battalion is moving in a staggered column formation.": "ðə bəˈtæliən ɪz ˈmuːvɪŋ ɪn ə ˈstæɡərd ˈkɑːləm fɔːrˈmeɪʃən",
    "Hold your position until the reinforcements arrive.": "hoʊld jər pəˈzɪʃən ənˈtɪl ðə ˌriːɪnˈfɔːrsmənt əˈraɪv",
    
    # Nhóm 3: Vô tuyến
    "This is Eagle One, do you copy? Over.": "ðɪs ɪz ˈiːɡəl wʌn duː juː ˈkɑːpi ˈoʊvər",
    "I read you loud and clear, proceed with your report.": "aɪ rɛd juː laʊd ənd klɪr proʊˈsid wɪð jər rɪˈpɔːrt",
    "Say again your last transmission, signal is weak.": "seɪ əˈɡɛn jər læst trænzˈmɪʃən ˈsɪɡnəl ɪz wik",
    "We have reached the objective, mission accomplished.": "wi hæv ritʃt ðə əbˈdʒɛktɪv ˈmɪʃən ˈækkɑːmplɪʃt",
    "Requesting a Situation Report from all units.": "rɪˈkwɛstɪŋ ə ˌsɪtʃuˈeɪʃən rɪˈpɔːrt frəm ɔːl ˈjuːnɪts",
    "The convoy is under attack, requesting immediate backup.": "ðə ˈkɑːnvɔɪ ɪz ˈʌndər əˈtæk rɪˈkwɛstɪŋ ɪˈmiːdiət ˈbækʌp",
    "Identify yourself before approaching the checkpoint.": "aɪˈdɛntɪˌfaɪ jɔːrˈsɛlf bɪˈfɔːr əˈproʊtʃɪŋ ðə ˈtʃɛkˌpɔɪnt",
    "Roger that, we will stand by for further instructions.": "ˈrɑːdʒər ðæt wi wɪl stænd baɪ fɔːr ˈfɜːðər ɪnˈstrʌkʃənz",
    "All units, be advised of enemy movement in sector four.": "ɔːl ˈjuːnɪts bi ədˈvaɪzd əv ˈɛnəmi ˈmuːvmənt ɪn ˈsɛktər fɔːr",
    "What is your current status and location?": "wɑːt ɪz jər ˈkɜːrənt ˈsteɪtəs ənd loʊˈkeɪʃən",
    "We have one priority casualty requiring evacuation.": "wi hæv wʌn praɪˈɔːrɪti ˈkæʒuəlti rɪˈkwaɪrɪŋ ɛvækjuˈeɪʃən",
    "The radio frequency has been jammed by the enemy.": "ðə ˈreɪdioʊ ˈfrikwənsi həz bɪn dʒæmd baɪ ðə ˈɛnəmi",
    "Confirm receipt of the new rules of engagement.": "kənˈfɜːrm rɪˈsit əv ðə nju ˈrulz əv ɪnˈɡeɪdʒmənt",
    "Use the phonetic alphabet to spell the location.": "juːz ðə fəˈnɛtɪk ˈælfəˌbɛt tuː spɛl ðə loʊˈkeɪʃən",
    "Our GPS signal is lost, switching to map and compass.": "aʊr ˌdʒiːpiːˈɛs ˈsɪɡnəl ɪz lɔːst ˈswɪtʃɪŋ tuː mæp ənd ˈkʌmpəs",
    "Report any suspicious activity to the headquarters.": "rɪˈpɔːrt ˈɛni səˈspɪʃəs ækˈtɪvɪti tuː ðə ˈhɛdˌkwɔːrtərz",
    "Maintain contact with the friendly forces on your right.": "ˈmeɪnˌteɪn ˈkɑːntækt wɪð ðə ˈfrɛndli ˈfɔːrsɪz ɑːn jər raɪt",
    "All clear, the area has been secured.": "ɔːl klɪr ðə ˈɛriə həz bɪn sɪˈkjʊrd",
    "Affirmative, the supplies will arrive in ten minutes.": "əˈfɜːrmətɪv ðə səˈplaɪz wɪl əˈraɪv ɪn tɛn ˈmɪnɪts",
    
    # Nhóm 4: Huấn luyện
    "Discipline is the backbone of a strong army.": "ˈdɪsəplɪn ɪz ðə ˈbeɪkˌboʊn əv ə strɔːŋ ˈɑːrmi",
    "You must follow the standard operating procedures at all times.": "juː məst ˈfɑːloʊ ðə ˈstændərd ˌɑːpəˈreɪtɪŋ ˈproʊsiːdʒərz æt ɔːl taɪmz",
    "All soldiers must keep their weapons clean and ready.": "ɔːl ˈsoʊldʒərz məst kip ðɛr ˈwɛpənz klin ənd ˈrɛdi",
    "This exercise simulates a real combat environment.": "ðɪs ˈɛksərˌsaɪz ˈsɪmjəˌleɪts ə ril ˈkɑːmbæt ɪnˈvaɪrənmənt",
    "Pay attention to the safety regulations during live-fire drills.": "peɪ əˈtɛnʃən tuː ðə ˈseɪfti ˌrɛɡjuˈleɪʃənz ˈdʊrɪŋ laɪv faɪər drɪlz",
    "Every soldier is responsible for their own gear.": "ˈɛvri ˈsoʊldʒər ɪz rɪˈspɑːnsɪbəl fɔːr ðɛr oʊn ɡɪr",
    "Practice makes perfect in mine clearance operations.": "ˈpræktɪs meɪks ˈpɜːrfɪkt ɪn maɪn ˈklɪrəns ˌɑːpəˈreɪʃənz",
    "You need to improve your reaction time in the field.": "juː niːd tuː ɪmˈpruːv jər riˈækʃən taɪm ɪn ðə fild",
    "Physical fitness is essential for every combat engineer.": "ˈfɪzɪkəl ˈfɪtnɪs ɪz ɪˈsɛnʃəl fɔːr ˈɛvri ˈkɑːmbæt ɛndʒɪˈnɪr",
    "The commander will inspect the barracks this afternoon.": "ðə kəˈmændər wɪl ɪnˈspɛkt ðə ˈbærəks ðɪs ˌæftərˈnun",
    "Learn how to read military maps and grid coordinates.": "lɜːrn haʊ tuː rid ˈmɪləteri mæps ənd ɡrɪd koʊˈɔːrdənɪts",
    "First aid training is mandatory for all personnel.": "fɜːrst eɪd ˈtreɪnɪŋ ɪz ˈmændətɔːri fɔːr ɔːl ˈpɜːrsəˌnɛl",
    "Do not leave your post without being properly relieved.": "duː nɑːt liv jər poʊst wɪðˈaʊt biːɪŋ ˈproʊpərli rɪˈlivd",
    "Loyalty and courage are the values of our unit.": "ˈlɔɪəlti ənd ˈkɜːrɪdʒ ɑːr ðə ˈvæljuːz əv aʊr ˈjuːnɪt",
    "The trainees are learning how to use the new detectors.": "ðə ˈtreɪniːz ɑːr ˈlɜːrnɪŋ haʊ tuː juːz ðə nju dɪˈtɛktərz",
    "Check your gas mask for any leaks before the drill.": "tʃɛk jər ɡæs mæsk fɔːr ˈɛni liks bɪˈfɔːr ðə drɪl",
    "We are conducting a joint exercise with the air force.": "wi ɑːr kənˈdʌktɪŋ ə dʒɔɪnt ˈɛksərˌsaɪz wɪð ðə ɛr fɔːrs",
    "Follow the chain of command for all formal requests.": "ˈfɑːloʊ ðə tʃeɪn əv kəˈmænd fɔːr ɔːl ˈfɔːrməl rɪˈkwɛsts",
    "You must pass the obstacle course within five minutes.": "juː məst pæs ðə ˈɑːbstækəl kɔːrs wɪðˈɪn faɪv ˈmɪnɪts",
    "Survival skills are crucial in a long-term operation.": "sərˈvaɪvəl skɪlz ɑːr ˈkruːʃəl ɪn ə ˌlɔːŋ tɜːrm ˌɑːpəˈreɪʃən",
    "The debriefing will start immediately after the mission.": "ðə diˈbriːfɪŋ wɪl stɑːrt ɪˈmiːdiətli ˈæftər ðə ˈmɪʃən",
    "Always wear your helmet and bulletproof vest in the field.": "ˈɔːlweɪz wɛr jər ˈhɛlmɪt ənd ˈbʊlɪtˌpruf vɛst ɪn ðə fild",
    "Knowledge of foreign languages is an advantage in peacekeeping.": "ˈnɑːlɪdʒ əv ˈfɔːrɪn ˈlæŋɡwɪdʒɪz ɪz əˌn ədˈvæntɪdʒ ɪn ˈpisˌkiːpɪŋ",
    "Stay alert and never underestimate the enemy.": "steɪ əˈlɜːrt ənd ˈnɛvər ˌʌndəˈrɛstɪmeɪt ðə ˈɛnəmi",
    "Professionalism is expected from every member of this team.": "prəˈfɛʃənəˌlɪzəm ɪz ɪkˈspɛktɪd frəm ˈɛvri ˈmɛmbər əv ðɪs tim",
}