# Từ điển cấp độ Từ (Word) - Unit 3: Military Engineering Vehicles
# Tiếng Anh : Tiếng Việt

word_dict = {
    # Categories: Engineering Equipment & Vehicles
    "Vehicle": "xe máy",
    "Bulldozer": "xe ủi",
    "Excavator": "máy đào đất",
    "Tractor": "xe kéo",
    "Crane": "cần trục",
    "Grader": "máy lấy bằng mặt đất",
    "Loader": "máy xúc",
    "Backhoe": "máy xúc đưới",
    "Dump truck": "xe tải đổ",
    "Tank": "xe tăng",
    "Armor": "thép bọc",
    "Caterpillar": "bánh xích",
    "Blade": "lưỡi gạt",
    "Bucket": "gầu múc",
    "Shovel": "xúc đất",
    "Track": "bánh răng",
    "Winch": "tời",
    "Turret": "tháp súng",
    "Hatch": "cửa sập",
    "Engine": "động cơ",
    
    # Engineering Operations
    "Construction": "xây dựng",
    "Fortification": "công sự",
    "Trench": "hào",
    "Excavation": "đào đất",
    "Transportation": "vận chuyển",
    "Digging": "đào bới",
    "Backfill": "san lấp",
    "Tunneling": "đào hầm",
    "Bridge building": "xây dựng cầu",
    "Road construction": "xây dựng đường",
    "Terrain": "địa hình",
    "Soil": "đất",
    "Rock": "đá",
    "Marsh": "đầm lầy",
    "Obstacle": "chướng ngại",
    
    # Combat & Military
    "Combat engineer": "công binh chiến đấu",
    "Military engineer": "kỹ sư quân sự",
    "Battlefield": "chiến trường",
    "Fortification": "công sự",
    "Mine": "mìn",
    "Unexploded ordnance": "hỏa lực nổ chậm",
    "Artillery": "pháo binh",
    "Blast": "vụ nổ",
    "Fragmentation": "mảnh vỡ",
    "Protection": "bảo vệ",
    
    # Technical Specifications
    "Specification": "tính năng kĩ thuật",
    "Capacity": "công suất",
    "Mobility": "khả năng cơ động",
    "Propulsion": "trục truyền động",
    "Power": "công suất",
    "Weight": "trọng lượng",
    "Speed": "tốc độ",
    "Diameter": "đường kính",
    "Depth": "chiều sâu",
    "Height": "chiều cao",
}

# Phiên âm quốc tế (IPA) cho các từ
word_ipa_dict = {
    "Vehicle": "ˈviːəkəl",
    "Bulldozer": "ˈbʊlˌdoʊzər",
    "Excavator": "ˈɛks.kə.veɪ.tər",
    "Tractor": "ˈtræk.tər",
    "Crane": "kreɪn",
    "Grader": "ˈɡreɪ.dər",
    "Loader": "ˈloʊ.dər",
    "Backhoe": "ˈbæk.hoʊ",
    "Dump truck": "dʌmp trʌk",
    "Tank": "tæŋk",
    "Armor": "ˈɑːr.mər",
    "Caterpillar": "ˈkæt.ər.pɪl.ər",
    "Blade": "bleɪd",
    "Bucket": "ˈbʌk.ɪt",
    "Shovel": "ˈʃʌv.əl",
    "Track": "træk",
    "Winch": "wɪntʃ",
    "Turret": "ˈtɜːr.ɪt",
    "Hatch": "hætʃ",
    "Engine": "ˈɛn.dʒɪn",
    "Construction": "kənˈstrʌk.ʃən",
    "Fortification": "ˌfɔːr.tɪ.fɪˈkeɪ.ʃən",
    "Trench": "trɛntʃ",
    "Excavation": "ˌɛk.skə.ˈveɪ.ʃən",
    "Transportation": "ˌtræns.pər.ˈteɪ.ʃən",
    "Digging": "ˈdɪɡ.ɪŋ",
    "Backfill": "ˈbæk.fɪl",
    "Tunneling": "ˈtʌn.əl.ɪŋ",
    "Bridge building": "brɪdʒ ˈbɪl.dɪŋ",
    "Road construction": "roʊd kənˈstrʌk.ʃən",
    "Terrain": "təˈreɪn",
    "Soil": "sɔɪl",
    "Rock": "rɑːk",
    "Marsh": "mɑːrʃ",
    "Obstacle": "ˈɑːb.stə.kəl",
    "Combat engineer": "ˈkɑːm.bæt ˌɛn.dʒɪˈnɪr",
    "Military engineer": "ˈmɪl.ɪˌtɛr.i ˌɛn.dʒɪˈnɪr",
    "Battlefield": "ˈbæt.əl.fild",
    "Fortification": "ˌfɔːr.tɪ.fɪˈkeɪ.ʃən",
    "Mine": "maɪn",
    "Unexploded ordnance": "ʌn.ɪkˈsploʊ.dɪd ˈɔːrd.nəns",
    "Artillery": "ɑːrˈtɪl.ə.ri",
    "Blast": "blæst",
    "Fragmentation": "ˌfræɡ.mənˈteɪ.ʃən",
    "Protection": "prəˈtɛk.ʃən",
    "Specification": "ˌspɛs.ɪ.fɪˈkeɪ.ʃən",
    "Capacity": "kəˈpæs.ɪ.ti",
    "Mobility": "moʊˈbɪl.ɪ.ti",
    "Propulsion": "prəˈpʌl.ʃən",
    "Power": "ˈpaʊ.ər",
    "Weight": "weɪt",
    "Speed": "spiːd",
    "Diameter": "daɪˈæm.ɪ.tər",
    "Depth": "dɛpθ",
    "Height": "haɪt",
}
