# Từ điển cấp độ Cụm từ (Phrase) - Unit 3: Military Engineering Vehicles
# Tiếng Anh : Tiếng Việt

phrase_dict = {
    # Engineering Operations & Tasks
    "Construction work": "công trình xây dựng",
    "Digging trenches": "đào hào",
    "Building fortifications": "xây dựng công sự",
    "Excavating soil": "đào đất",
    "Transporting equipment": "vận chuyển thiết bị",
    "Operating machinery": "vận hành máy móc",
    "Clearing obstacles": "dọn sạch chướng ngại",
    "Moving heavy equipment": "di chuyển thiết bị nặng",
    "Laying foundations": "đặt nền móng",
    "Backfilling trenches": "san lấp hào",
    
    # Vehicle Characteristics
    "Military engineering vehicles": "xe máy công binh",
    "Armored bulldozer": "xe ủi bọc thép",
    "Caterpillar tractor": "xe kéo bánh xích",
    "Heavy equipment": "thiết bị nặng",
    "Cross-country vehicle": "xe cơ động qua mọi địa hình",
    "Purpose-built military vehicle": "xe quân sự được xây dựng đặc biệt",
    "Mechanized equipment": "thiết bị cơ giới",
    "Hydraulic-powered": "do thủy lực vận hành",
    "Diesel-powered engine": "động cơ chạy dầu diesel",
    "High mobility": "khả năng cơ động cao",
    
    # Combat Engineering
    "Combat engineer": "công binh chiến đấu",
    "Mine clearance": "rà phá bom mìn",
    "Explosives disposal": "xử lý chất nổ",
    "Battlefield hazards": "nguy hiểm trên chiến trường",
    "Small arms protection": "bảo vệ chống súng nhỏ",
    "Artillery fragments": "mảnh vỡ pháo binh",
    "Unexploded ordnance": "hỏa lực nổ chậm",
    "Creating passages": "tạo lối đi",
    "Breaching obstacles": "vô hiệu hóa chướng ngại",
    "Rapid deployment": "triển khai nhanh",
    
    # Technical Operations
    "Lifting and lowering": "nâng lên và hạ xuống",
    "Operating the blade": "vận hành lưỡi gạt",
    "Controlling the bucket": "điều khiển gầu múc",
    "Adjusting hydraulics": "điều chỉnh thủy lực",
    "Maximizing efficiency": "tối đa hóa hiệu suất",
    "Reducing vibration": "giảm rung động",
    "Increasing torque": "tăng mô men xoắn",
    "Decreasing fuel consumption": "giảm tiêu hao nhiên liệu",
    "Improving maneuverability": "cải thiện khả năng điều quân",
    "Enhancing stability": "tăng cường tính ổn định",
    
    # Terrain & Conditions
    "Harsh terrain": "địa hình khắc nghiệt",
    "Soft ground": "mặt đất mềm",
    "Rocky soil": "đất đá",
    "Marshy area": "khu vực đầm lầy",
    "Muddy conditions": "điều kiện bùn lầy",
    "All-terrain capability": "khả năng hoạt động trên mọi địa hình",
    "Difficult environment": "môi trường khó khăn",
    "Flooded area": "khu vực ngập nước",
    "Frozen ground": "mặt đất đóng băng",
    "Desert conditions": "điều kiện sa mạc",
    
    # Safety & Protection
    "Armor plating": "tấm bọc thép",
    "Blast protection": "bảo vệ chống vụ nổ",
    "Fragmentation shield": "lá chắn chống mảnh vỡ",
    "Safety procedures": "quy trình an toàn",
    "Protective gear": "thiết bị bảo vệ",
    "Structural reinforcement": "gia cố cấu trúc",
    "Impact resistance": "khả năng chịu tác động",
    "Fireproofing measures": "biện pháp chống cháy",
    "Emergency protocols": "quy trình ứng cứu",
    "Personnel safety": "an toàn nhân sự",
}

# Phiên âm quốc tế (IPA) cho các cụm từ
phrase_ipa_dict = {
    "Construction work": "kənˈstrʌk.ʃən wɜːrk",
    "Digging trenches": "ˈdɪɡ.ɪŋ trɛntʃ.ɪz",
    "Building fortifications": "ˈbɪl.dɪŋ ˌfɔːr.tɪ.fɪˈkeɪ.ʃənz",
    "Excavating soil": "ˈɛk.skə.veɪt.ɪŋ sɔɪl",
    "Transporting equipment": "trænˈspɔːrt.ɪŋ ɪˈkwɪp.mənt",
    "Operating machinery": "ˈɑːp.ə.reɪt.ɪŋ məˈʃiːn.ə.ri",
    "Clearing obstacles": "ˈklɪr.ɪŋ ˈɑːb.stə.kəlz",
    "Moving heavy equipment": "ˈmuːv.ɪŋ ˈhɛv.i ɪˈkwɪp.mənt",
    "Laying foundations": "ˈleɪ.ɪŋ faʊnˈdeɪ.ʃənz",
    "Backfilling trenches": "ˈbæk.fɪl.ɪŋ trɛntʃ.ɪz",
    "Military engineering vehicles": "ˈmɪl.ɪˌtɛr.i ˌɛn.dʒɪˈnɪr.ɪŋ ˈviː.ə.kəlz",
    "Armored bulldozer": "ˈɑːr.mərd ˈbʊl.ˌdoʊ.zər",
    "Caterpillar tractor": "ˈkæt.ər.pɪl.ər ˈtræk.tər",
    "Heavy equipment": "ˈhɛv.i ɪˈkwɪp.mənt",
    "Cross-country vehicle": "krɔːs ˈkʌn.tri ˈviː.ə.kəl",
    "Purpose-built military vehicle": "ˈpɜːr.pəs bɪlt ˈmɪl.ɪˌtɛr.i ˈviː.ə.kəl",
    "Mechanized equipment": "ˈmɛk.ə.naɪzd ɪˈkwɪp.mənt",
    "Hydraulic-powered": "haɪˈdrɔː.lɪk ˈpaʊ.ərd",
    "Diesel-powered engine": "ˈdiː.zəl ˈpaʊ.ərd ˈɛn.dʒɪn",
    "High mobility": "haɪ moʊˈbɪl.ɪ.ti",
    "Combat engineer": "ˈkɑːm.bæt ˌɛn.dʒɪˈnɪr",
    "Mine clearance": "maɪn ˈklɪr.əns",
    "Explosives disposal": "ɪkˈsploʊ.sɪvz dɪsˈpoʊ.zəl",
    "Battlefield hazards": "ˈbæt.əl.fild ˈhæz.ərdz",
    "Small arms protection": "smɔːl ɑːrmz prəˈtɛk.ʃən",
    "Artillery fragments": "ɑːrˈtɪl.ə.ri ˈfræɡ.mənts",
    "Unexploded ordnance": "ʌn.ɪkˈsploʊ.dɪd ˈɔːrd.nəns",
    "Creating passages": "kriˈeɪt.ɪŋ ˈpæs.ɪ.dʒɪz",
    "Breaching obstacles": "ˈbritʃ.ɪŋ ˈɑːb.stə.kəlz",
    "Rapid deployment": "ˈræp.ɪd dɪˈplɔɪ.mənt",
    "Lifting and lowering": "ˈlɪft.ɪŋ ənd ˈloʊ.ə.rɪŋ",
    "Operating the blade": "ˈɑːp.ə.reɪt.ɪŋ ðə bleɪd",
    "Controlling the bucket": "kənˈtroʊl.ɪŋ ðə ˈbʌk.ɪt",
    "Adjusting hydraulics": "əˈdʒʌst.ɪŋ haɪˈdrɔː.lɪks",
    "Maximizing efficiency": "ˈmæk.sɪ.maɪz.ɪŋ ɪˈfɪʃ.ən.si",
    "Reducing vibration": "rɪˈduː.sɪŋ vaɪˈbreɪ.ʃən",
    "Increasing torque": "ɪnˈkris.ɪŋ tɔːrk",
    "Decreasing fuel consumption": "dɪˈkris.ɪŋ ˈfjuː.əl kənˈsʌmp.ʃən",
    "Improving maneuverability": "ɪmˈpruːv.ɪŋ məˌnuː.vər.əˈbɪl.ɪ.ti",
    "Enhancing stability": "ɛnˈhæns.ɪŋ stəˈbɪl.ɪ.ti",
    "Harsh terrain": "hɑːrʃ təˈreɪn",
    "Soft ground": "sɔːft graʊnd",
    "Rocky soil": "ˈrɑː.ki sɔɪl",
    "Marshy area": "ˈmɑːr.ʃi ˈɛr.i.ə",
    "Muddy conditions": "ˈmʌd.i kənˈdɪʃ.ənz",
    "All-terrain capability": "ɔːl təˈreɪn kəˈpæb.ɪl.ɪ.ti",
    "Difficult environment": "ˈdɪf.ɪ.kəlt ɪnˈvaɪ.rən.mənt",
    "Flooded area": "ˈflaʊ.dɪd ˈɛr.i.ə",
    "Frozen ground": "ˈfroʊ.zən graʊnd",
    "Desert conditions": "ˈdɛz.ərt kənˈdɪʃ.ənz",
    "Armor plating": "ˈɑːr.mər ˈpleɪt.ɪŋ",
    "Blast protection": "blæst prəˈtɛk.ʃən",
    "Fragmentation shield": "ˌfræɡ.mənˈteɪ.ʃən ʃild",
    "Safety procedures": "ˈseɪf.ti prəˈsid.jərz",
    "Protective gear": "prəˈtɛk.tɪv ɡɪr",
    "Structural reinforcement": "ˈstrʌk.tʃər.əl ˌriː.ɪnˈfɔːrs.mənt",
    "Impact resistance": "ˈɪm.pækt rɪˈzɪs.təns",
    "Fireproofing measures": "ˈfaɪər.ˌpruː.fɪŋ ˈmɛʒ.ərz",
    "Emergency protocols": "ɪˈmɜːr.dʒən.si ˈproʊ.tə.kɔːlz",
    "Personnel safety": "ˈpɜːr.sə.nəl ˈseɪf.ti",
}
