# Từ điển cấp độ Cụm từ (Phrase) - Unit 4: Bomb - Mine, Fortifications
# Tiếng Anh : Tiếng Việt

phrase_dict = {
    # Fortification Construction & Design
    "Military construction": "công trình quân sự",
    "Defensive works": "công trình phòng thủ",
    "Permanent fortification": "công sự vĩnh viễn",
    "Field fortification": "công sự tác chiến",
    "Semi-permanent fortification": "công sự bán vĩnh viễn",
    "Designing fortifications": "thiết kế công sự",
    "Building fortifications": "xây dựng công sự",
    "City walls": "tường thành phố",
    "Defensive territory": "lãnh thổ phòng thủ",
    "Military base": "căn cứ quân sự",
    
    # Mine Operations
    "Landmine clearance": "xử lý quả mìn",
    "Mine detection": "phát hiện mìn",
    "Mine clearing": "dọn sạch mìn",
    "Anti-tank mines": "mìn chống xe tăng",
    "Anti-personnel mines": "mìn chống nhân sự",
    "Detecting mines": "phát hiện mìn",
    "Clearing mines": "dọn sạch mìn",
    "Metal detector": "máy dò kim loại",
    "Mine probe": "cái dò phát hiện mìn",
    "Tripwire trap": "bẫy dây dẫn mìn",
    
    # Demining Process
    "Checking for tripwires": "kiểm tra dây dẫn mìn",
    "Clearing vegetation": "dọn sạch cây cỏ",
    "Studying terrain": "nghiên cứu địa hình",
    "Checking with probe": "kiểm tra bằng cái dò",
    "Marking mines": "đánh dấu mìn",
    "Destroying mines": "phá hủy mìn",
    "Body armor": "áo chống đạn",
    "Protective visor": "mặt nạ bảo vệ",
    "Safety procedures": "quy trình an toàn",
    "Demining procedure": "quy trình xử lý mìn",
    
    # Siege & Warfare
    "Laying siege": "bao vây",
    "Destroying fortification": "phá hủy công sự",
    "Siege warfare": "chiến tranh bao vây",
    "Civil war": "nội chiến",
    "Military campaign": "chiến dịch quân sự",
    "Combat operations": "hoạt động chiến đấu",
    "Warfare tactics": "chiến thuật chiến tranh",
    "Defensive position": "vị trí phòng thủ",
    "Strategic location": "vị trí chiến lược",
    "Military deployment": "triển khai quân sự",
    
    # Chemical Weapons
    "Chemical weapons": "vũ khí hóa học",
    "War gases": "khí độc chiến tranh",
    "Mustard gas": "hơi vàng",
    "Nerve gas": "hơi thần kinh",
    "Gas attack": "tấn công bằng khí độc",
    "Toxic chemicals": "hóa chất độc hại",
    "Biological weapons": "vũ khí sinh học",
    "Weapon stockpile": "kho vũ khí",
    "Area contamination": "ô nhiễm khu vực",
    "Casualty rate": "tỷ lệ thương vong",
    
    # Casualties & Health
    "High casualty": "thương vong cao",
    "Civilian casualties": "thương vong dân thường",
    "Military casualties": "thương vong quân sự",
    "Injury prevention": "phòng chống chấn thương",
    "Medical assistance": "hỗ trợ y tế",
    "Health hazard": "nguy hiểm sức khỏe",
    "War victim": "nạn nhân chiến tranh",
    "Rehabilitation center": "trung tâm phục hồi",
    "Prosthetic limb": "chi giả",
    "Disability support": "hỗ trợ người khuyết tật",
    
    # Resources & Materials
    "Local labour": "lao động địa phương",
    "Building materials": "vật liệu xây dựng",
    "Enduring materials": "vật liệu bền vững",
    "Military resources": "tài nguyên quân sự",
    "State resources": "tài nguyên của nhà nước",
    "Construction equipment": "thiết bị xây dựng",
    "Skilled workers": "công nhân lành nghề",
    "Mechanical skill": "kỹ năng cơ khí",
    "Technical expertise": "chuyên môn kỹ thuật",
    "Expert assistance": "sự giúp đỡ của chuyên gia",
}

# Phiên âm quốc tế (IPA) cho các cụm từ
phrase_ipa_dict = {
    "Military construction": "ˈmɪl.ɪˌtɛr.i kənˈstrʌk.ʃən",
    "Defensive works": "dɪˈfɛn.sɪv wɜːrks",
    "Permanent fortification": "ˈpɜːr.mə.nənt ˌfɔːr.tɪ.fɪˈkeɪ.ʃən",
    "Field fortification": "fild ˌfɔːr.tɪ.fɪˈkeɪ.ʃən",
    "Semi-permanent fortification": "ˌsɛm.i ˈpɜːr.mə.nənt ˌfɔːr.tɪ.fɪˈkeɪ.ʃən",
    "Designing fortifications": "dɪˈzaɪn.ɪŋ ˌfɔːr.tɪ.fɪˈkeɪ.ʃənz",
    "Building fortifications": "ˈbɪl.dɪŋ ˌfɔːr.tɪ.fɪˈkeɪ.ʃənz",
    "City walls": "ˈsɪt.i wɔːlz",
    "Defensive territory": "dɪˈfɛn.sɪv ˈtɛr.ə.tɔːr.i",
    "Military base": "ˈmɪl.ɪˌtɛr.i beɪs",
    "Landmine clearance": "ˈlænd.maɪn ˈklɪr.əns",
    "Mine detection": "maɪn dɪˈtɛk.ʃən",
    "Mine clearing": "maɪn ˈklɪr.ɪŋ",
    "Anti-tank mines": "ˌæn.ti tæŋk maɪnz",
    "Anti-personnel mines": "ˌæn.ti ˌpɜːr.sə.nəl maɪnz",
    "Detecting mines": "dɪˈtɛk.tɪŋ maɪnz",
    "Clearing mines": "ˈklɪr.ɪŋ maɪnz",
    "Metal detector": "ˈmɛt.əl dɪˈtɛk.tər",
    "Mine probe": "maɪn proʊb",
    "Tripwire trap": "ˈtrɪp.waɪər træp",
    "Checking for tripwires": "ˈtʃɛk.ɪŋ fɔːr ˈtrɪp.waɪərz",
    "Clearing vegetation": "ˈklɪr.ɪŋ ˌvɛdʒ.əˈteɪ.ʃən",
    "Studying terrain": "ˈstʌd.i.ɪŋ təˈreɪn",
    "Checking with probe": "ˈtʃɛk.ɪŋ wɪð proʊb",
    "Marking mines": "ˈmɑːrk.ɪŋ maɪnz",
    "Destroying mines": "dɪˈstrɔɪ.ɪŋ maɪnz",
    "Body armor": "ˈbɑː.di ˈɑːr.mər",
    "Protective visor": "prəˈtɛk.tɪv ˈvaɪ.zər",
    "Safety procedures": "ˈseɪf.ti prəˈsid.ʒərz",
    "Demining procedure": "diˈmaɪn.ɪŋ prəˈsid.ʒər",
    "Laying siege": "ˈleɪ.ɪŋ sidʒ",
    "Destroying fortification": "dɪˈstrɔɪ.ɪŋ ˌfɔːr.tɪ.fɪˈkeɪ.ʃən",
    "Siege warfare": "sidʒ ˈwɔːr.fer",
    "Civil war": "ˈsɪv.əl wɔːr",
    "Military campaign": "ˈmɪl.ɪˌtɛr.i kæmˈpeɪn",
    "Combat operations": "ˈkɑːm.bæt ˌɑːp.əˈreɪ.ʃənz",
    "Warfare tactics": "ˈwɔːr.fer ˈtæk.tɪks",
    "Defensive position": "dɪˈfɛn.sɪv pəˈzɪʃ.ən",
    "Strategic location": "strəˈtid.ʒɪk loʊˈkeɪ.ʃən",
    "Military deployment": "ˈmɪl.ɪˌtɛr.i dɪˈplɔɪ.mənt",
    "Chemical weapons": "ˈkɛm.ɪ.kəl ˈwɛp.ənz",
    "War gases": "wɔːr ˈɡæs.ɪz",
    "Mustard gas": "ˈmʌs.tərd ɡæs",
    "Nerve gas": "nɜːrv ɡæs",
    "Gas attack": "ɡæs əˈtæk",
    "Toxic chemicals": "ˈtɑːk.sɪk ˈkɛm.ɪ.kəlz",
    "Biological weapons": "ˌbaɪ.oʊˈlɑːdʒ.ɪ.kəl ˈwɛp.ənz",
    "Weapon stockpile": "ˈwɛp.ən ˈstɑːk.paɪl",
    "Area contamination": "ˈɛr.i.ə ˌkɑːn.tæm.ɪˈneɪ.ʃən",
    "Casualty rate": "ˈkæʒ.u.əl.ti reɪt",
    "High casualty": "haɪ ˈkæʒ.u.əl.ti",
    "Civilian casualties": "sɪˈvɪl.yən ˈkæʒ.u.əl.tiz",
    "Military casualties": "ˈmɪl.ɪˌtɛr.i ˈkæʒ.u.əl.tiz",
    "Injury prevention": "ˈɪn.dʒə.ri prɪˈvɛn.ʃən",
    "Medical assistance": "ˈmɛd.ɪ.kəl əˈsɪs.təns",
    "Health hazard": "hɛlθ ˈhæz.ərd",
    "War victim": "wɔːr ˈvɪk.tɪm",
    "Rehabilitation center": "ˌriː.ə.bɪl.ɪˈteɪ.ʃən ˈsɛn.tər",
    "Prosthetic limb": "prɑːsˈθɛt.ɪk lɪm",
    "Disability support": "dɪsˌæb.ɪl.ɪ.ti səˈpɔːrt",
    "Local labour": "ˈloʊ.kəl ˈleɪ.bər",
    "Building materials": "ˈbɪl.dɪŋ məˈtɪr.i.əlz",
    "Enduring materials": "ɛnˈdʊr.ɪŋ məˈtɪr.i.əlz",
    "Military resources": "ˈmɪl.ɪˌtɛr.i ˈrɛ.sɔːrsɪz",
    "State resources": "steɪt ˈrɛ.sɔːrsɪz",
    "Construction equipment": "kənˈstrʌk.ʃən ɪˈkwɪp.mənt",
    "Skilled workers": "skɪld ˈwɜːr.kərz",
    "Mechanical skill": "məˈkæn.ɪ.kəl skɪl",
    "Technical expertise": "ˈtɛk.nɪ.kəl ˌɛk.spərˈtiz",
    "Expert assistance": "ˈɛk.spɜːrt əˈsɪs.təns",
}
