# Từ điển cấp độ Từ (Word) - Unit 4: Bomb - Mine, Fortifications
# Tiếng Anh : Tiếng Việt

word_dict = {
    # Fortifications & Structures
    "Fortification": "công sự",
    "Fort": "pháo đài",
    "Fortress": "pháo đài lớn",
    "Fortalice": "công sự nhỏ",
    "Castle": "lâu đài",
    "Wall": "bức tường",
    "Breastwork": "công sự ngoài",
    "Sandbag": "bao cát",
    "Bunker": "lô cốt",
    "Trench": "hào",
    
    # Mines & Explosives
    "Mine": "mìn",
    "Landmine": "quả mìn",
    "Anti-tank mine": "mìn chống xe tăng",
    "Anti-personnel mine": "mìn chống nhân sự",
    "Bomb": "bom",
    "Explosive": "chất nổ",
    "UXO": "mìn không nổ",
    "Detonator": "ngòi nổ",
    "Tripwire": "dây dẫn mìn",
    "Boobytrap": "bẫy độc",
    
    # Demining Operations
    "Demining": "xử lý mìn",
    "Demine": "xử lý mìn",
    "Detection": "dò phát hiện",
    "Detect": "dò phát hiện",
    "Detector": "máy dò",
    "Metal detector": "máy dò kim loại",
    "Probe": "cái dò mìn",
    "Clearance": "dọn sạch",
    "Clearing": "dọn sạch",
    "Deminer": "người xử lý mìn",
    
    # Chemical Weapons
    "Gas": "hơi độc",
    "Chemical weapon": "vũ khí hóa học",
    "Mustard gas": "hơi nhân tạo",
    "Nerve gas": "hơi thần kinh",
    "Hydrogen cyanide": "xyanua hyđro",
    "Phosphorus": "phân tử lân",
    
    # Military Terms
    "Warfare": "chiến trường",
    "Civil war": "nội chiến",
    "Siege": "bao vây",
    "Defence": "phòng thủ",
    "Base": "căn cứ",
    "Troop": "quân lính",
    "Casualty": "thương vong",
    "Terrain": "địa hình",
    "Campaign": "chiến dịch",
    "Soldier": "binh lính",
    
    # Equipment & Gear
    "Visor": "mặt nạ bảo vệ",
    "Armor": "áo giáp",
    "Body armor": "áo chống đạn",
    "Helmet": "mũ cối",
    "Gloves": "găng tay",
    "Boots": "giày chiến đấu",
    "Uniform": "quân phục",
    
    # Technical Terms
    "Construction": "xây dựng",
    "Design": "thiết kế",
    "Installation": "cài đặt",
    "Deployment": "triển khai",
    "Designation": "chỉ định",
    "Classification": "phân loại",
    "Terminal": "cuối cùng",
    "Procedure": "quy trình",
    "Protection": "bảo vệ",
    "Safety": "an toàn",
}

# Phiên âm quốc tế (IPA) cho các từ
word_ipa_dict = {
    "Fortification": "ˌfɔːr.tɪ.fɪˈkeɪ.ʃən",
    "Fort": "fɔːrt",
    "Fortress": "ˈfɔːr.trəs",
    "Fortalice": "ˈfɔːr.tə.lis",
    "Castle": "ˈkæs.əl",
    "Wall": "wɔːl",
    "Breastwork": "ˈbrɛst.wɜːrk",
    "Sandbag": "ˈsænd.bæɡ",
    "Bunker": "ˈbʌŋ.kər",
    "Trench": "trɛntʃ",
    "Mine": "maɪn",
    "Landmine": "ˈlænd.maɪn",
    "Anti-tank mine": "ˌæn.ti tæŋk maɪn",
    "Anti-personnel mine": "ˌæn.ti ˌpɜːr.sə.nəl maɪn",
    "Bomb": "bɑːm",
    "Explosive": "ɪkˈsploʊ.sɪv",
    "UXO": "ˌjuːɛks ˈoʊ",
    "Detonator": "ˈdɛt.ə.neɪ.tər",
    "Tripwire": "ˈtrɪp.waɪər",
    "Boobytrap": "ˈbuː.bi.træp",
    "Demining": "diˈmaɪn.ɪŋ",
    "Demine": "diˈmaɪn",
    "Detection": "dɪˈtɛk.ʃən",
    "Detect": "dɪˈtɛkt",
    "Detector": "dɪˈtɛk.tər",
    "Metal detector": "ˈmɛt.əl dɪˈtɛk.tər",
    "Probe": "proʊb",
    "Clearance": "ˈklɪr.əns",
    "Clearing": "ˈklɪr.ɪŋ",
    "Deminer": "diˈmaɪn.ər",
    "Gas": "ɡæs",
    "Chemical weapon": "ˈkɛm.ɪ.kəl ˈwɛp.ən",
    "Mustard gas": "ˈmʌs.tərd ɡæs",
    "Nerve gas": "nɜːrv ɡæs",
    "Hydrogen cyanide": "ˈhaɪ.drə.dʒən ˈsaɪ.ə.naɪd",
    "Phosphorus": "ˈfɑːs.fər.əs",
    "Warfare": "ˈwɔːr.fer",
    "Civil war": "ˈsɪv.əl wɔːr",
    "Siege": "sidʒ",
    "Defence": "dɪˈfɛns",
    "Base": "beɪs",
    "Troop": "truːp",
    "Casualty": "ˈkæʒ.u.əl.ti",
    "Terrain": "təˈreɪn",
    "Campaign": "kæmˈpeɪn",
    "Soldier": "ˈsoʊl.dʒər",
    "Visor": "ˈvaɪ.zər",
    "Armor": "ˈɑːr.mər",
    "Body armor": "ˈbɑː.di ˈɑːr.mər",
    "Helmet": "ˈhɛl.mɪt",
    "Gloves": "ɡlʌvz",
    "Boots": "buːts",
    "Uniform": "ˈjuː.nɪ.fɔːrm",
    "Construction": "kənˈstrʌk.ʃən",
    "Design": "dɪˈzaɪn",
    "Installation": "ˌɪn.stəˈleɪ.ʃən",
    "Deployment": "dɪˈplɔɪ.mənt",
    "Designation": "ˌdɛz.ɪɡˈneɪ.ʃən",
    "Classification": "ˌklæs.ɪ.fɪˈkeɪ.ʃən",
    "Terminal": "ˈtɜːr.mɪ.nəl",
    "Procedure": "prəˈsid.ʒər",
    "Protection": "prəˈtɛk.ʃən",
    "Safety": "ˈseɪf.ti",
}
