# Từ điển cấp độ Từ (Word) - Tiếng Anh : Tiếng Việt
# 100 Từ Vựng Tiếng Anh Quân Sự Thông Dụng Nhất

military_dict = {
    # Organization & Ranks (Các đơn vị và Cấp bậc)
    "Army": "Lục quân",
    "Unit": "Đơn vị",
    "Headquarters": "Bộ chỉ huy",
    "Squad": "Tiểu đội",
    "Platoon": "Trung đội",
    "Company": "Đại đội",
    "Battalion": "Tiểu đoàn",
    "Regiment": "Trung đoàn",
    "Brigade": "Lữ đoàn",
    "Division": "Sư đoàn",
    "Corps": "Quân đoàn",
    "Officer": "Sĩ quan",
    "Commissioned Officer": "Sĩ quan chỉ huy",
    "Non-commissioned Officer": "Hạ sĩ quan",
    "Private": "Binh nhì",
    "Corporal": "Hạ sĩ",
    "Sergeant": "Trung sĩ",
    "Lieutenant": "Trung úy",
    "Captain": "Đại úy",
    "Major": "Thiếu tá",
    "Colonel": "Đại tá",
    "General": "Tướng",
    
    # Operations & Tactics (Tác chiến và Chiến thuật)
    "Mission": "Nhiệm vụ",
    "Operation": "Chiến dịch/Hoạt động",
    "Combat": "Chiến đấu",
    "Strategy": "Chiến lược",
    "Tactics": "Chiến thuật",
    "Deployment": "Triển khai quân",
    "Maneuver": "Điều quân/Diễn tập",
    "Reconnaissance": "Trinh sát",
    "Intelligence": "Tình báo",
    "Ambush": "Phục kích",
    "Assault": "Đột kích/Tấn công",
    "Defense": "Phòng thủ",
    "Counter-attack": "Phản công",
    "Retreat": "Rút lui",
    "Reinforcement": "Viện binh",
    "Logistics": "Hậu cần",
    "Patrol": "Tuần tra",
    "Target": "Mục tiêu",
    "Objective": "Mục tiêu chiến dịch",
    "Casualty": "Thương vong",
    "Engagement": "Giao tranh",
    
    # Weapons & Equipment (Vũ khí và Trang bị)
    "Weapon": "Vũ khí",
    "Firearm": "Súng trường/Súng ngắn",
    "Ammunition": "Đạn dược",
    "Artillery": "Pháo binh",
    "Infantry": "Bộ binh",
    "Armored Vehicle": "Xe bọc thép",
    "Tank": "Xe tăng",
    "Helicopter": "Trực thăng",
    "Radar": "Ra-đa",
    "Radio": "Máy thông tin",
    "Gas mask": "Mặt nạ phòng độc",
    "Bulletproof vest": "Áo chống đạn",
    "Helmet": "Mũ cối/Mũ bảo hiểm quân sự",
    "Camouflage": "Ngụy trang",
    "Supplies": "Quân nhu",
    
    # Combat Engineering (Chuyên ngành Công binh - Trọng tâm)
    "Combat Engineer": "Chiến sĩ công binh",
    "Sapper": "Công binh",
    "Demolition": "Phá hủy/Đánh bộc phá",
    "Explosive": "Chất nổ",
    "Mine": "Mìn",
    "Landmine": "Mìn bộ binh",
    "Sea mine": "Thủy lôi",
    "Minefield": "Bãi mìn",
    "Mine clearance": "Rà phá mìn",
    "Detector": "Máy dò",
    "IED": "Thiết bị nổ tự chế",
    "UXO": "Vật nổ chưa nổ",
    "Detonator": "Kíp nổ",
    "Fuse": "Ngòi nổ",
    "TNT": "Thuốc nổ TNT",
    "Plastic explosive": "Thuốc nổ dẻo",
    "Fortification": "Công sự",
    "Trench": "Chiến hào",
    "Bunker": "Lô cốt/Hầm trú ẩn",
    "Barbed wire": "Dây thép gai",
    "Obstacle": "Vật cản",
    "Bridge building": "Bắc cầu",
    "Pontoon bridge": "Cầu phao",
    "Bailey bridge": "Cầu dã chiến Bailey",
    "Excavation": "Đào đất/Khai quật",
    "Earthworks": "Công trình đất",
    "Road construction": "Xây dựng đường sá",
    "Decontamination": "Tẩy độc",
    "Breaching": "Phá rào/Mở đường",
    
    # General Terms (Thuật ngữ chung và Khác)
    "Order": "Mệnh lệnh",
    "Discipline": "Kỷ luật",
    "Base": "Căn cứ",
    "Barracks": "Doanh trại",
    "Checkpoint": "Trạm kiểm soát",
    "Curfew": "Lệnh giới nghiêm",
    "Drill": "Tập luyện/Diễn tập",
    "Field": "Thao trường/Chiến trường",
    "Invasion": "Sự xâm lược",
    "Occupation": "Sự chiếm đóng",
    "Peacekeeping": "Gìn giữ hòa bình",
    "Surrender": "Đầu hàng",
    "Uniform": "Quân phục",
}

# Phiên âm quốc tế (IPA) cho 100 từ quân sự
military_ipa_dict = {
    # Organization & Ranks
    "Army": "ˈɑːrmi",
    "Unit": "ˈjuːnɪt",
    "Headquarters": "ˈhɛdkwɔːrtərz",
    "Squad": "skwɑːd",
    "Platoon": "pləˈtuːn",
    "Company": "ˈkʌmpəni",
    "Battalion": "bəˈtæliən",
    "Regiment": "ˈrɛdʒɪmənt",
    "Brigade": "brɪˈɡeɪd",
    "Division": "dɪˈvɪʒən",
    "Corps": "kɔːr",
    "Officer": "ˈɑːfɪsər",
    "Commissioned Officer": "kəˈmɪʃənd ˈɑːfɪsər",
    "Non-commissioned Officer": "ˌnɑːn kəˈmɪʃənd ˈɑːfɪsər",
    "Private": "ˈpraɪvɪt",
    "Corporal": "ˈkɔːrprəl",
    "Sergeant": "ˈsɑːrdʒənt",
    "Lieutenant": "luːˈtɛnənt",
    "Captain": "ˈkæptən",
    "Major": "ˈmeɪdʒər",
    "Colonel": "ˈkɜːrnəl",
    "General": "ˈdʒɛnərəl",
    
    # Operations & Tactics
    "Mission": "ˈmɪʃən",
    "Operation": "ɑːpəˈreɪʃən",
    "Combat": "ˈkɑːmbæt",
    "Strategy": "ˈstrætədʒi",
    "Tactics": "ˈtæktɪks",
    "Deployment": "dɪˈplɔɪmənt",
    "Maneuver": "məˈnuːvər",
    "Reconnaissance": "rɪˈkɑːnəsəns",
    "Intelligence": "ɪnˈtɛlɪdʒəns",
    "Ambush": "ˈæmbʊʃ",
    "Assault": "əˈsɔːlt",
    "Defense": "dɪˈfɛns",
    "Counter-attack": "ˈkaʊntər əˈtæk",
    "Retreat": "rɪˈtriːt",
    "Reinforcement": "ˌriːɪnˈfɔːrsmənt",
    "Logistics": "loʊˈdʒɪstɪks",
    "Patrol": "pəˈtroʊl",
    "Target": "ˈtɑːrɡɪt",
    "Objective": "əbˈdʒɛktɪv",
    "Casualty": "ˈkæʒuəlti",
    "Engagement": "ɪnˈɡeɪdʒmənt",
    
    # Weapons & Equipment
    "Weapon": "ˈwɛpən",
    "Firearm": "ˈfaɪərɑːrm",
    "Ammunition": "ˌæmjuˈnɪʃən",
    "Artillery": "ɑːrˈtɪləri",
    "Infantry": "ˈɪnfəntri",
    "Armored Vehicle": "ˈɑːrmərd ˈviːɪkəl",
    "Tank": "tæŋk",
    "Helicopter": "ˈhɛlɪkɑːptər",
    "Radar": "ˈreɪdɑːr",
    "Radio": "ˈreɪdioʊ",
    "Gas mask": "ɡæs mæsk",
    "Bulletproof vest": "ˈbʊlɪtˈpruf vɛst",
    "Helmet": "ˈhɛlmɪt",
    "Camouflage": "ˈkæməflɑːʒ",
    "Supplies": "səˈplaɪz",
    
    # Combat Engineering
    "Combat Engineer": "ˈkɑːmbæt ɛndʒɪˈnɪr",
    "Sapper": "ˈsæpər",
    "Demolition": "ˌdɛməˈlɪʃən",
    "Explosive": "ɪkˈsploʊsɪv",
    "Mine": "maɪn",
    "Landmine": "ˈlændˌmaɪn",
    "Sea mine": "siː maɪn",
    "Minefield": "ˈmaɪnˌfild",
    "Mine clearance": "maɪn ˈklɪrəns",
    "Detector": "dɪˈtɛktər",
    "IED": "ˌaɪiːˈɛd",
    "UXO": "ˌjuːɛksˈoʊ",
    "Detonator": "ˈdɛtəˌneɪtər",
    "Fuse": "fjuːz",
    "TNT": "ˌtiːɛnˈti",
    "Plastic explosive": "ˈplæstɪk ɪkˈsploʊsɪv",
    "Fortification": "ˌfɔːrtɪfɪˈkeɪʃən",
    "Trench": "trɛntʃ",
    "Bunker": "ˈbʌŋkər",
    "Barbed wire": "ˈbɑːrbd ˈwaɪər",
    "Obstacle": "ˈɑːbstækəl",
    "Bridge building": "brɪdʒ ˈbɪldɪŋ",
    "Pontoon bridge": "pɑːnˈtuːn brɪdʒ",
    "Bailey bridge": "ˈbeɪli brɪdʒ",
    "Excavation": "ˌɛkskəˈveɪʃən",
    "Earthworks": "ˈɜːrθˌwɜːrks",
    "Road construction": "roʊd kənˈstrʌkʃən",
    "Decontamination": "ˌdiːkənˌtæmɪˈneɪʃən",
    "Breaching": "ˈbriːtʃɪŋ",
    
    # General Terms
    "Order": "ˈɔːrdər",
    "Discipline": "ˈdɪsəplɪn",
    "Base": "beɪs",
    "Barracks": "ˈbærəks",
    "Checkpoint": "ˈtʃɛkˌpɔɪnt",
    "Curfew": "ˈkɜːrfjuː",
    "Drill": "drɪl",
    "Field": "fild",
    "Invasion": "ɪnˈveɪʒən",
    "Occupation": "ˌɑːkjuˈpeɪʃən",
    "Peacekeeping": "ˈpisˌkiːpɪŋ",
    "Surrender": "səˈrɛndər",
    "Uniform": "ˈjuːnɪfɔːrm",
}

# Gộp lại để sử dụng cho chế độ luyện tập tổng hợp
word_dict = military_dict

# Gộp IPA dict
word_ipa_dict = military_ipa_dict